<?php
use Flywheel\Document\Html;
use Flywheel\View\Render;

/** @var Render $this */
/** @var Html $document */

$document = $this->document();
$document->addJs('js/process/contact.js', 'BOTTOM');

?>

<div class="padding">

    <div class="row">
        <div class="col-sm-8 col-xs-12">

            <ol class="breadcrumb">
                <li><a href="">Trang chủ</a></li>
                <li class="active">Liên hệ</li>
            </ol>

            <div class="list-group">
                <a href="javascript:" class="list-group-item text-uppercase">
                    Thông tin liên hệ
                </a>

                <div class="list-group-item">
                    <div class="row">
                        <div class="col-sm-8 col-sm-offset-2">

                            <div class="form-group text-center">
                                <?php echo \Setting::get('info_contact_form') ?>
                            </div>



                            <form class="form-horizontal" id="_form">
                                <div class="form-group">
                                    <label for="fullname" class="col-sm-3 control-label">Họ tên <span class="text-danger">*</span></label>
                                    <div class="col-sm-8">
                                        <input autofocus name="fullname" type="text" class="form-control" id="fullname" placeholder="">
                                    </div>
                                </div>


                                <div class="form-group">
                                    <label for="address" class="col-sm-3 control-label">Địa chỉ <span class="text-danger">*</span></label>
                                    <div class="col-sm-8">
                                        <input name="address" type="text" class="form-control" id="address" placeholder="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="mobiphone" class="col-sm-3 control-label">Điện thoại <span class="text-danger">*</span></label>
                                    <div class="col-sm-8">
                                        <input name="mobiphone" type="text" class="form-control" id="mobiphone" placeholder="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="email" class="col-sm-3 control-label">Email <span class="text-danger">*</span></label>
                                    <div class="col-sm-8">
                                        <input name="email" type="email" class="form-control" id="email" placeholder="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="subject" class="col-sm-3 control-label">Tiêu đề <span class="text-danger">*</span></label>
                                    <div class="col-sm-8">
                                        <input name="subject" type="text" class="form-control" id="subject" placeholder="">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="content" class="col-sm-3 control-label">Nội dung <span class="text-danger">*</span></label>
                                    <div class="col-sm-9">
                                        <textarea id="content" name="content" rows="6" class="form-control"></textarea>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-9">
                                        <button type="button" class="btn btn-danger" id="_btn-save">Gửi liên hệ</button>

                                        <button type="reset" class="btn btn-default">Làm lại</button>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="col-sm-4 col-xs-12">
            <?php include __DIR__ .'/../../sidebar.php'; ?>
        </div>
    </div>

</div>