<?php
/** @var $widget */
/** @var Terms $term */
use Flywheel\Document\Html;
/** @var Html $document */
$document = $this->document();
?>

<!-- begin selection -->
<div class="section" id="section5">
    <div id="selection" class="animateblock btm" data-id="6rdPage">
        <div class="container">
            <h1><?php echo $widget->term->getName() ?></h1>

            <?php if(sizeof($widget->list) > 0){
                    $class = [
                        ['c' => 'one', 'i' => '<i class="fa fa-code"></i>'],
                        ['c' => 'two', 'i' => '<i class="fa fa-dollar"></i>'],
                        ['c' => 'three', 'i' => '<i class="">D</i>']
                    ];
                ?>
            <?php
                for($i = 0, $size = sizeof($widget->list); $i < $size; ++$i){
                $item = $widget->list[$i];
                if($item instanceof \Posts){
                    $detail_link = $controller->createUrl('post/detail', array('id' => $item->getId()));
                    $img = $item->getMainImg();
                    ?>
                        <div class="col-sm-4 col-xs-12">
                            <div class="box-sm <?php echo isset($class[$i]) ? $class[$i]['c'] : 'one' ?>">
                                <div class="icon">
                                    <?php echo isset($class[$i]) ? $class[$i]['i'] : 'one' ?>
                                </div>

                                <div class="right">
                                    <div class="title">
                                        <a href="<?php echo $detail_link ?>" target="_blank">
                                            <?php echo $item->getTitle() ?>
                                        </a>
                                    </div>
                                    <div class="description"><?php echo $item->getExcerpt() ?></div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                <?php } ?>
            <?php } ?>

            <div class="footer">
                <ul>
                    <li>
                        <i class="fa fa-envelope"></i>
                        <a target="_blank" href="mailto:<?php echo \Setting::get('recruitment_email'); ?>"><?php echo \Setting::get('recruitment_email'); ?></a>
                    </li>
                    <li>
                        <i class="fa fa-phone-square"></i>
                        <a href="javascript:"><?php echo \Setting::get('recruitment_phone'); ?></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>