<?php
/** @var $widget */
/** @var Terms $term */
use Flywheel\Document\Html;
/** @var Html $document */
$document = $this->document();
?>

<!-- begin introduction -->
<div class="section" id="section2">
    <div id="introduction" class="animateblock right" data-id="3rdPage">
        <div class="container">
            <h1><?php echo $widget->term->getName() ?></h1>
            <?php if(sizeof($widget->list) > 0){ ?>
            <ul>
                <?php
                for($i = 0, $size = sizeof($widget->list); $i < $size; ++$i){
                    $item = $widget->list[$i];
                    if($item instanceof \Posts){
                        $detail_link = $controller->createUrl('post/detail', array('id' => $item->getId()));
                        $img = $item->getMainImg();
                    ?>
                    <li>
                        <h5><?php echo $item->getTitle() ?></h5>

                        <div class="description">
                            <?php echo $item->getContent() ?>
                        </div>

                        <div class="line-space">***</div>
                    </li>
                    <?php } ?>
                <?php } ?>
            </ul>
            <?php } ?>

            <?php if($widget->term_id > 0){ ?>
                <a target="_blank" class="btn btn-view-more hidden-xs" href="<?php echo $controller->createUrl('category/default', array('id' => $widget->term_id)) ?>">
                    TÌM HIỂU THÊM
                </a>
            <?php } ?>
        </div>
    </div>
</div>