<?php
/** @var SlideShow $widget */
use Flywheel\Document\Html;
/** @var Html $document */
$document = $this->document();
?>

<?php if (!empty($widget->banners)) :?>
    <div class="box-tour">
        <div class="box-tour-header">
            <h3><a href="javascript:">Quảng cáo</a></h3>
        </div>
        <div class="box-tour-body">

            <ul class="list-adv">
                <?php for($i = 0, $size=sizeof($widget->banners); $i < $size; ++$i) :?>
                    <?php
                    $banner = $widget->banners[$i];
                    ?>
                        <li>
                            <a href="<?php echo $banner->getLink() ?>" target="<?php echo $banner->getLinkTarget() ?>">
                                <img width="100%" src="<?php echo \Setting::get('site_url') . $banner->getFile(); ?>" />
                            </a>
                        </li>
                <?php endfor; ?>
            </ul>

        </div>
    </div>
<?php endif; ?>

