<?php
/** @var SlideShow $widget */
use Flywheel\Document\Html;
/** @var Html $document */
$document = $this->document();
?>

<!-- begin slider -->

    <script>
        $(document).ready(function(){
            $('.bxslider').bxSlider({
                mode: 'fade',
                caption: true,
                adaptiveHeight: true
            });
        });
    </script>

    <?php if (!empty($widget->banners)) :?>
        <ul class="bxslider">
            <?php for($i = 0, $size=sizeof($widget->banners); $i < $size; ++$i) :?>
                <?php
                $banner = $widget->banners[$i];
//                var_dump($banner);
                ?>
                <li>
                    <a href="<?php echo $banner->getLink() ?>" target="<?php echo $banner->getLinkTarget() ?>">
                        <img src="<?php echo \Setting::get('site_url') . $banner->getFile(); ?>" />
                    </a>
                </li>
            <?php endfor; ?>
        </ul>
    <?php endif; ?>

